name: Build LaTeX Resume

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex  # Your main .tex file
        args: -pdf -file-line-error -halt-on-error
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update resume.pdf
        file_pattern: resume.pdf
